### ISSUE TITLE
Access Denied starting ComObject

### ISSUE THREAD

**Issue by CarteKiwi** [smourier/VCamNetSample#1]
Hello Simon, 

Thanks for this great work !
Exactly what I was looking for right now :)

I was not able to use **regsvr32** as you said:
`regsvr32 VCamNetSampleSource.dll`
(that was raising an error "DllRegisterServer not found")

Had to call it on the ComHost file:
`regsvr32 VCamNetSampleSource.comhost.dll`

But, I now get an "access denied" when instantiating camera in Main.cs of client app.
`hr = _camera.Object.Start(null);`

Any idea ? 
I'm on Windows 11

Thanks

**Comment by smourier** [comment]
Hi,

Aw... of course you need to register the comhost.dll (this was an incorrect copy paste from the native version https://github.com/smourier/VCamSample)

As for the access denied, it's probably the same issue as for the native version https://github.com/smourier/VCamSample/issues/1

Here is a summary:

* The COM object that serves as a Virtual Camera Source (here `VCamNetSampleSource.comhost.dll`) must be accessible by the two Windows 11 services **Frame Server** & **Frame Server Monitor** (running as `svchost.exe`).
* These two services usually run as *Local Service* & *Local System* credentials respectively.
* If you compile or build in a directory under your compiling user's root, for example something like `C:\Users\<your login>\source\repos\VCamNetSample\VCamNetSampleSource\bin\Debug\net8.0-windows10.0.22621.0` or somewhere restricted in some way, **it won't work** since these two services will need to access that.

=> So the solution is just to either copy the output directory once built (or downloaded) somewhere where everyone has access and register  `VCamNetSampleSource.comhost.dll` from there, or copy/checkout the whole repo where everyone has access and build and register there.

**Comment by CarteKiwi** [comment]
Crystal clear :)
It's working now. Thanks for your prompt reply !
